config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get 'search' => 'searches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource  :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment,presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.book_id = @book.id
    if @comment.save
      render :post_comments
    else
      render 'book/show'
    end

    # redirect_back(fallback_location: root_path)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    @book = Book.find(params[:book_id])
    render :post_comments
    # redirect_back(fallback_location: root_path)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_from.html.erb
<%= form_with model: [@book, post_comment],  local: false do |f| %>
  <%= f.text_area :comment, size: '90x5' %><br>
  <%= f.submit "送信" %>
<% end %>

app/views/post_comments/_post_comments.html.erb
<table>
  <% book.post_comments.each do |post_comment| %>
  <tr>
    <td>
      <%= link_to user_path(post_comment.user) do %>
      <%= image_tag post_comment.user.get_profile_image, size:"100x100" %><br>
      <%= post_comment.user.name %>
      <% end %>
    </td>
    <td>
      <%= post_comment.comment %>
    </td>
    <% if post_comment.user == current_user %>
    <td>
      <%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/post_comments/post_comments.js.erb
$('#comments_area').html("<%= j(render 'post_comments/post_comments', book: @book, comment: @comment) %>");
$("textarea").val('');